package nastasia.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;


public class MessageBox extends JFrame {


    private JPanel panel1;
    private JTextArea messageArea;
    private JPasswordField passwordField1;


    // ****************************************************

    public String getPass() {
        return new String(passwordField1.getPassword());
    }


    public MessageBox(String message) {
        super("Message");
        setContentPane(panel1);
//        frame.setSize(300, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        messageArea.setText(message);
        pack();
        setVisible(true);

//        connectButton.addActionListener(actionEvent ->  );

    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
//        orderByComboBox = new JComboBox<>(OrderBy.values());
//        orderByComboBox.setSelectedItem(OrderBy.MATCH_RATING);
//        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
//        orderByComboBox.setModel(defaultComboBoxModel1);
//        panel3.add(orderByComboBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        messageArea = new JTextArea();
        messageArea.setEditable(false);
        messageArea.setText("");
        scrollPane1.setViewportView(messageArea);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }


    // ************************************************************************

}